name: Build & Test the project # optionnal
run-name: ${{ github.actor }} is building the project and testing the project # optionnal

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }} # clé associé au cache (ici pour le node module)

      - run: |
          npm ci
          npm run build
          ls -lah

  test:
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        browser: ['chrome', 'firefox', 'edge']
    steps:
      - name: Chechckout
        uses: actions/checkout@v3
      - name: Cache Primes
        id: cache-primes
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }} # clé associé au cache (ici pour le node module)
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0 # use the explicit version number
        with:
          build: npm run build
          start: npm run start
          browser: ${{ matrix.browser }}
      - uses: actions/upload-artifact@v2 # les artéfacts "sont les assets", ça permet de montrer la vidéos ou la capture d'écran et de pouvoir la télécharger 
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
      - uses: actions/upload-artifact@v2 
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots